## Given these home prices find out price of a home that has,

## 3000 sqr ft area, 3 bedrooms, 40 year old

## 2500 sqr ft area, 4 bedrooms, 5 year old

In [ ]:

import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:

df = pd.read_excel('homeprice.xlsx')
df

area  bedrooms  age   price
0  2200       3.0   21  550080
1  3200       4.0   15  565500
2  3800       NaN   17  614520
3  3600       3.0   31  595000
4  4200       5.0    7  765400
5  4700       6.0    8  812000

area  bedrooms  age   price
0  2200       3.0   21  550080
1  3200       4.0   15  565500
2  3800       NaN   17  614520
3  3600       3.0   31  595000
4  4200       5.0    7  765400
5  4700       6.0    8  812000

## Data Preprocessing: Fill NA values with median value of a column

In [ ]:
df.bedrooms.median()

4.0

4.0

In [ ]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2200       3.0   21  550080
1  3200       4.0   15  565500
2  3800       4.0   17  614520
3  3600       3.0   31  595000
4  4200       5.0    7  765400
5  4700       6.0    8  812000

area  bedrooms  age   price
0  2200       3.0   21  550080
1  3200       4.0   15  565500
2  3800       4.0   17  614520
3  3600       3.0   31  595000
4  4200       5.0    7  765400
5  4700       6.0    8  812000

In [ ]:

reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

LinearRegression()

In [ ]:
reg.coef_


array([3.90735881e+01, 6.74228140e+04, 6.65430171e+02])

array([3.90735881e+01, 6.74228140e+04, 6.65430171e+02])

In [ ]:
reg.intercept_


217192.5333842957

217192.5333842957

## Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old

In [ ]:
reg.predict([[3000, 3, 40]])


array([563298.9466546])

array([563298.9466546])

In [ ]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540384


498408.25157402386

498408.25157402386

## Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old

In [ ]:
reg.predict([[2500, 4, 5]])


array([587894.91062733])

array([587894.91062733])